language: node_js
node_js:
    - '10'
cache:
    directories:
        - node_modules
#  package.json and yarn.lockhe   npm install: yarn
before_install:
    - npm install
# before_script:

script:
    - npm run prod
# deploy:
#     provider: pages
#     skip_cleanup: true
#     github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
#     keep_history: true
#     on:
#         branch: master
