language: node_js
node_js:
    - '10'
cache:
    directories:
        - node_modules
#  package.json and yarn.lockhe   npm install: yarn
before_install:
    - npm install
# before_script:

script:
    - npm run prod
